version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bumpp
  - dawidd6
  - hono
  - mkdist
  - nolyfill
  - taze
  - unocss
  - unplugin
  - Vite
  - vitepress
ignoreWords: []
import: []
