name: CI

on:
  push:
    paths-ignore:
      - 'docs/pages/**'
    branches:
      - main
  pull_request:
    paths-ignore:
      - 'docs/pages/**'
    branches:
      - main

env:
  STORE_PATH: ''

jobs:
  unittest:
    strategy:
      matrix:
        node-version: ['24.x']

    name: Unit tests - ${{ matrix.node-version }}
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v5

      # Turborepo
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run test:run

  lint:
    strategy:
      matrix:
        node-version: ['24.x']

    name: Lint - ${{ matrix.node-version }}
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v5

      # Turborepo
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run lint

  packages-build-test:
    strategy:
      matrix:
        node-version: ['24.x']

    name: Packages Build Test - ${{ matrix.node-version }}
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v5

      # Turborepo
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm run build:packages
